# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_admin', models.CharField(max_length=50)),
                ('apellidos_admin', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellidos_cliente', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('año', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_habitacion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(choices=[('1', 'Ocupada'), ('0', 'Desocupada')], default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservar.Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservar.Admin')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservar.Cliente')),
                ('fecha_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fecha_in', to='reservar.Fecha')),
                ('fecha_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fecha_out', to='reservar.Fecha')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservar.Habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpago', models.CharField(choices=[('E', 'Efectivo'), ('T', 'Tarjeta')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservar.Reserva'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipopago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservar.TipoPago'),
        ),
    ]
