# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='apellidos_admin',
            new_name='nombre_completo_admin',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='dni',
            new_name='dni_cliente',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='nombre_admin',
        ),
    ]
